import Head from 'next/head'
import ImageSliders from '../components/ImageSliders'
// import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ImageSliders />
      </main>


    </div>
  )
}
